### ISSUE TITLE
--overwrite fails

### ISSUE THREAD

**Issue by mattloose** [KolmogorovLab/hapdup#21]
[2022-11-03 20:16:22] INFO: Filtering alignments
Traceback (most recent call last):
  File "/data/test_data/GIT/hapdup/hapdup.py", line 24, in <module>
    sys.exit(main())
  File "/data/test_data/GIT/hapdup/hapdup/main.py", line 153, in main
    filter_alignments_parallel(args.bam, filtered_bam, min(args.threads, 30),
  File "/data/test_data/GIT/hapdup/hapdup/filter_misplaced_alignments.py", line 188, in filter_alignments_parallel
    pysam.merge("-@", str(num_threads), bam_out, *bams_to_merge)
  File "/home/plzmwl/anaconda3/envs/hapdup/lib/python3.8/site-packages/pysam/utils.py", line 69, in __call__
    raise SamtoolsError(
pysam.utils.SamtoolsError: "samtools returned with error 1: stdout=, stderr=[bam_merge] File 'hapdup/filtered.bam' exists. Please apply '-f' to overwrite. Abort.\n"

Looks as though when you run with --overwrite the command is not being correctly passed through to sub processes.

**Comment by fenderglass** [comment]
Oups! Will try to fix it soon.

**Comment by fenderglass** [comment]
Just pushed a commit that should fix the problem. Haven't updated the docker image yet, but looks like you are using source builds.. Let me know if that works!

Misha
