### ISSUE TITLE
unexpected keyword argument 'index_filename'

### ISSUE THREAD

**Issue by rmormando** [KolmogorovLab/hapdup#26]
Hi I'm trying to run HapDup on my Flye assembly using this command:

`./hapdup.py --assembly ../flye.fasta --bam ../flye_LR.bam --bam-index ../flye_LR.bai --out-dir ../hapdup --rtype ont`

But for some reason I keep getting this error message:

```
[2023-02-23 20:54:19] INFO: Filtering alignments
Traceback (most recent call last):
  File "/home/ec2-user/hapdup/./hapdup.py", line 24, in <module>
    sys.exit(main())
  File "/home/ec2-user/hapdup/hapdup/main.py", line 153, in main
    filter_alignments_parallel(args.bam, filtered_bam, min(args.threads, 30),
  File "/home/ec2-user/hapdup/hapdup/filter_misplaced_alignments.py", line 157, in filter_alignments_parallel
    all_reference_ids = [r for r in pysam.AlignmentFile(bam_in, "rb", index_filename=bam_index).references]
  File "pysam/calignmentfile.pyx", line 340, in pysam.calignmentfile.AlignmentFile.__cinit__
  File "pysam/calignmentfile.pyx", line 378, in pysam.calignmentfile.AlignmentFile._open
TypeError: _open() got an unexpected keyword argument 'index_filename'

```

Anyone know a way to fix it?

**Comment by fenderglass** [comment]
Assuming this has been resolved, feel free to follow up if not!
