### ISSUE TITLE
Problem running HapDup

### ISSUE THREAD

**Issue by mwjraats** [KolmogorovLab/hapdup#29]
Hi,

I have problems installing/running HapDup, I followed the source installation to create a specific conda env for HapDup. This went completely well as far as I know, but then when I want to run HapDup I get the following error:

[2023-06-05 18:34:16] INFO: Skipped filtering phase
[2023-06-05 18:34:16] INFO: Running: pepper_variant call_variant -b /data/volume_2/minimap/kit9/hapdup/filtered.bam -f /data/volume_2/minimap/kit9/fasta/assembly.fasta -o /data/volume_
2/minimap/kit9/hapdup/pepper -m hapdup/pepper/pepper_model.bin -t 10 -s Sample --ont_r9_guppy5_sup --include-supplementary --no_quantized 2>&1 |tee hapdup/pepper/pepper.log
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError: returned a result with an error set
/home/mraats/.local/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/mraats/.local/lib/python3.8/site-packages/torchvision/image│····
.so: undefined symbol: _ZN3c104impl8GPUTrace13gpuTraceStateE'If you don't plan on using image functionality from torchvision.io, you can ignore this warning. Otherwise, there might be somethin│····
g wrong with your environment. Did you have libjpeg or libpng installed before building torchvision from source?
warn(
Traceback (most recent call last):
File "/home/mraats/.local/bin/pepper_variant", line 5, in
from pepper_variant.pepper_variant import main
File "/home/mraats/.local/lib/python3.8/site-packages/pepper_variant/pepper_variant.py", line 12, in
from pepper_variant.modules.python.RunInference import run_inference
File "/home/mraats/.local/lib/python3.8/site-packages/pepper_variant/modules/python/RunInference.py", line 6, in
from pepper_variant.modules.python.models.predict_distributed_cpu import predict_distributed_cpu
File "/home/mraats/.local/lib/python3.8/site-packages/pepper_variant/modules/python/models/predict_distributed_cpu.py", line 15, in │····
from pepper_variant.modules.python.models.dataloader_predict import SequenceDataset
File "/home/mraats/.local/lib/python3.8/site-packages/pepper_variant/modules/python/models/dataloader_predict.py", line 4, in │····
import torchvision.transforms as transforms
File "/home/mraats/.local/lib/python3.8/site-packages/torchvision/init.py", line 6, in
from torchvision import datasets, io, models, ops, transforms, utils
File "/home/mraats/.local/lib/python3.8/site-packages/torchvision/models/init.py", line 17, in
from . import detection, optical_flow, quantization, segmentation, video
File "/home/mraats/.local/lib/python3.8/site-packages/torchvision/models/quantization/init.py", line 3, in
from .mobilenet import *
File "/home/mraats/.local/lib/python3.8/site-packages/torchvision/models/quantization/mobilenet.py", line 1, in
from .mobilenetv2 import * # noqa: F401, F403
File "/home/mraats/.local/lib/python3.8/site-packages/torchvision/models/quantization/mobilenetv2.py", line 5, in
from torch.ao.quantization import DeQuantStub, QuantStub
ModuleNotFoundError: No module named 'torch.ao.quantization'
rm: cannot remove 'hapdup/pepper/images*': No such file or directory
rm: cannot remove 'hapdup/pepper/predictions*': No such file or directory
[2023-06-05 18:34:17] ERROR: Missing output: /data/volume_2/minimap/kit9/hapdup/pepper/PEPPER_VARIANT_FULL.vcf
Traceback (most recent call last):
File "/home/mraats/data/volume_2/hapdup/hapdup.py", line 24, in
sys.exit(main())
File "/data/volume_2/hapdup/hapdup/main.py", line 190, in main
file_check(pepper_vcf)
File "/data/volume_2/hapdup/hapdup/main.py", line 114, in file_check
raise Exception("Missing output")
Exception: Missing output

Do you perhaps have any idea how I could solve this?

**Comment by mwjraats** [comment]
I fixed it!
