### ISSUE TITLE
IndexError: list index out of range (using docker image)

### ISSUE THREAD

**Issue by JWDebler** [KolmogorovLab/hapdup#47]
Running this command eventually leads to hapdup docker version to complain

```
minimap2 -ax lr:hq -t $(nproc) Chr2.region.duplex.fastq.gz Chr2.region.simplex.fastq.gz | samtools sort -@ $(nproc)  > assembly_lr_mapping.bam && \
samtools index -@ $(nproc) assembly_lr_mapping.bam && \

HD_DIR=`pwd` && \
docker run -v $HD_DIR:$HD_DIR -u `id -u`:`id -g` mkolmogo/hapdup:torch110 \
  hapdup --assembly $HD_DIR/assembly.fasta \
  --bam $HD_DIR/assembly_lr_mapping.bam \
  --out-dir $HD_DIR/hapdup -t 1 --rtype ont
```
And this is the error:

```
[2024-11-05 11:19:50] INFO: Filtering alignments
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/hapdup/filter_misplaced_alignments.py", line 151, in filter_alignments
    if check_read_mapping_confidence(line, min_aligned_length, MIN_ALIGNED_RATE, max_read_error, MAX_SEGMENTS):
  File "/usr/local/lib/python3.8/dist-packages/hapdup/filter_misplaced_alignments.py", line 100, in check_read_mapping_confidence
    sa_fields[0], int(sa_fields[1]), sa_fields[2], sa_fields[3], int(sa_fields[5])
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/local/bin/hapdup", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/hapdup/main.py", line 153, in main
    filter_alignments_parallel(args.bam, filtered_bam, min(args.threads, 30),
  File "/usr/local/lib/python3.8/dist-packages/hapdup/filter_misplaced_alignments.py", line 184, in filter_alignments_parallel
    raise Exception("One of the processes exited with code: {0}".format(t.exitcode))
Exception: One of the processes exited with code: 1
```

This is on Ubuntu 22.04 and Docker version 27.3.1, build ce12230

hapdup docker image: mkolmogo/hapdup   torch110   f145a734f175

**Comment by JWDebler** [comment]
forgot to map against the actual assembly *facepalm* :-)
